In [10]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [15]:
# Supposons que 'data' est notre tableau de données
# TODO : extraire les données des pdf des étudiants

# Générer des réponses d'étudiants et des notes
responses = np.random.randint(0, 2, size=(100, 65))  # valeurs 0 ou 1
grades = np.random.uniform(0, 20, size=(100, 1))  # valeurs continues entre 0 et 20

# Concaténer les réponses et les notes pour obtenir le tableau de données
data = np.hstack((responses, grades))

print(data[:10])

[[ 1.          1.          1.          1.          1.          0.
   1.          0.          0.          0.          0.          1.
   0.          0.          1.          0.          1.          0.
   0.          1.          1.          1.          0.          0.
   1.          0.          0.          0.          1.          0.
   1.          0.          0.          1.          0.          0.
   1.          0.          1.          1.          1.          0.
   1.          0.          0.          1.          0.          1.
   0.          1.          1.          0.          1.          1.
   0.          0.          1.          0.          1.          0.
   0.          1.          1.          0.          1.          3.50195499]
 [ 1.          0.          0.          0.          1.          0.
   1.          1.          1.          1.          0.          1.
   1.          1.          1.          0.          0.          1.
   0.          1.          0.          0.          1.          0.
 

In [16]:
# Extraire les réponses et les notes
responses = data[:, :-1]
grades = data[:, -1]
print(responses)
print(grades)

[[1. 1. 1. ... 1. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [1. 1. 1. ... 0. 1. 0.]
 ...
 [1. 0. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 0. ... 0. 0. 1.]]
[ 3.50195499  4.99998    19.846803    7.48951663 11.30563232  9.54092815
 19.74192334 16.08208994  8.28688603 16.61058362 14.78312412  3.14184558
  7.73324359 14.47468757  5.85736174  4.68809503 10.92480352  5.00542489
 11.11387222 14.56491697  9.80632857  6.9452623   8.06920137  0.47095281
  6.25033507  7.4158897   7.79497883 11.75650864  2.64954392  3.82172624
 11.31883848 19.30484519 12.31880386  2.90201621 15.0179068  11.03198316
 12.19049544  6.77649465 19.19096617  2.36335274 14.94167193 11.76602883
 19.49889722  1.56090396  7.87889782 12.98581232 11.13002709 10.10044942
  9.67284899 10.83975048 11.4432269   4.73247817 13.21229082 18.21090161
 15.34073716  6.32688525  8.01364791 16.6701405   1.82225157  0.5753809
  3.45444187 10.05006013  8.31630183 10.14024956 17.24333649  5.81811088
  6.23276122 13.5999478   5.88370783  1.17

In [19]:
# Former un modèle de régression logistique pour chaque question
models = []
for i in range(65):
    model = LinearRegression()
    model.fit(responses[:, i:i+1], grades)
    models.append(model)

In [31]:
# Définir le seuil comme la moyenne des notes
threshold = grades.mean()

# Utiliser les modèles pour prédire les réponses correctes
correct_answers = []
for model in models:
    # Si la valeur prédite pour une réponse de 1 dépasse le seuil, on considère que la réponse est correcte
    value = model.predict([[1]])
    correct_answer = 1 if value > threshold else 0
    correct_answers.append(correct_answer)

print(correct_answers)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]


# OLD

In [30]:
# Autre idée (mais je pense que c'est naze) : utiliser un coefficient de corrélation
            
import numpy as np

# Générer des réponses d'étudiants et des notes
responses = np.random.randint(0, 2, size=(100, 65))  # valeurs 0 ou 1
grades = np.random.uniform(0, 20, size=(100, 1))  # valeurs continues entre 0 et 20

# Concaténer les réponses et les notes pour obtenir le tableau de données
data = np.hstack((responses, grades))

# Extraire les réponses et les notes
responses = data[:, :-1]
grades = data[:, -1]

# Calculer la corrélation entre chaque réponse et les notes
correlations = np.corrcoef(np.hstack((responses, grades.reshape(-1, 1))), rowvar=False)[-1, :-1]

# Les réponses avec une corrélation positive sont considérées comme correctes
correct_answers = (correlations > 0).astype(int)

print(correct_answers)

[0 1 0 0 1 0 1 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1
 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1 0 0 0 1 1 0 0]
